# Generated by Django 5.1.6 on 2025-02-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_policeofficer_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='policeofficer',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
